import { ProofSummary } from '../types';
import { computeMinimalCounterexample } from './counterexample';
import { generateRegressionTest } from './testGenerator';

export function generateBobHandoffMarkdown(summary: ProofSummary): string {
  const criticalFindings = summary.findings.filter((f) => f.severity === 'CRITICAL');

  const findingReports = criticalFindings
    .map((finding) => {
      const matchComparison = summary.comparisons.find((c) => c.scenario.id === finding.scenarioId);
      const scenario = matchComparison ? matchComparison.scenario : {
        id: finding.scenarioId,
        name: `${finding.role} ${finding.action} ${finding.resource}`,
        role: finding.role,
        resource: finding.resource,
        action: finding.action,
        conditions: finding.conditions,
      };

      const counterexample = computeMinimalCounterexample(finding, scenario);
      const testCode = generateRegressionTest(finding);

      return `## Finding: ${finding.id} — ${finding.classification}
- **Role Affected:** \`${finding.role}\`
- **Resource Affected:** \`${finding.resource}\`
- **Action Affected:** \`${finding.action}\`
- **Baseline Result:** \`${finding.baselineDecision}\` (${finding.baselineReason})
- **Candidate Result:** \`${finding.candidateDecision}\` (${finding.candidateReason})
- **Classification:** \`${finding.classification}\` (Severity: ${finding.severity})
- **Summary:** ${finding.summary}

### Minimal Counterexample
- **Target Role:** \`${counterexample.minimalFactors.role}\`
- **Resource:** \`${counterexample.minimalFactors.resource}\`
- **Action:** \`${counterexample.minimalFactors.action}\`
- **Key Deterministic Divergence Factor:** \`${counterexample.minimalFactors.criticalCondition}\`
- **Explanation:** ${counterexample.explanation}

### Generated Automated Regression Test
\`\`\`typescript
${testCode}
\`\`\`

### Suggested Next Investigation for IBM Bob
1. Inspect the candidate AST/code in \`src/engine/candidate.ts\` where \`${finding.resource}\` checks are executed.
2. Verify why the conditional \`${counterexample.minimalFactors.criticalCondition}\` was bypassed or corrupted during the refactor.
3. Apply the regression test to the test runner and verify it fails on the current candidate branch.
4. Patch the candidate policy to restore the \`${finding.baselineDecision}\` decision invariant.
5. Re-run \`PermitProof\` to certify that all critical findings are resolved and status changes to \`PROVEN\`.
`;
    })
    .join('\n---\n\n');

  return `# IBM BOB HANDOFF DOSSIER
**Generated by PermitProof for IBM Bob 2.0 Hackathon Investigation**

## Project Overview
- **Project Name:** ${summary.project}
- **Baseline Policy Version:** ${summary.baselineVersion}
- **Candidate Policy Version:** ${summary.candidateVersion}
- **Verification Result:** **${summary.status}**
- **Critical Security Regressions Detected:** ${summary.criticalCount} / ${summary.totalScenarios} Scenarios
- **Total Access Deltas:** ${summary.changedCount}

---

## Executive Summary for IBM Bob Autonomous Agent
PermitProof has deterministically evaluated the candidate policy against the production baseline. 
Critical authorization regressions were discovered that violate tenant isolation and role privilege boundaries.

Use this handoff document to instruct IBM Bob to investigate the policy refactoring commits, isolate the root cause lines of code, and apply automated patches.

---

${findingReports}

---

## Instructions for Loading into IBM Bob
1. Open your IBM Bob workspace session.
2. Provide this file (\`BOB_HANDOFF.md\`) or copy its contents into the IBM Bob prompt.
3. Prompt Bob:
   > *"I have received a PermitProof change failure certificate with ${summary.criticalCount} critical authorization regressions. Review the minimal counterexamples and generated Vitest tests in BOB_HANDOFF.md, locate the code defects in the authorization engine, apply the fixes, and run \`npm run test\` until all suites pass."*
4. Take a screenshot of the completed IBM Bob session summary and save it in \`bob_sessions/\`.
`;
}
