import { ProofSummary } from '../types';
import { generateRegressionTest } from './testGenerator';

export function generateCertificateMarkdown(summary: ProofSummary): string {
  const testsSection = summary.findings
    .filter((f) => f.severity === 'CRITICAL')
    .map((f) => `### Test for ${f.id} (${f.role} -> ${f.resource}:${f.action})\n\`\`\`typescript\n${generateRegressionTest(f)}\n\`\`\``)
    .join('\n\n');

  const findingsList = summary.findings
    .map(
      (f) =>
        `- **[${f.id}] ${f.severity}**: \`${f.role}\` → \`${f.resource}\` (\`${f.action}\`)\n` +
        `  - Baseline: \`${f.baselineDecision}\` → Candidate: \`${f.candidateDecision}\`\n` +
        `  - Type: \`${f.classification}\`\n` +
        `  - Detail: ${f.summary}`
    )
    .join('\n');

  return `# AUTHORIZATION CHANGE CERTIFICATE
*Generated by PermitProof Deterministic Engine*

- **Project:** ${summary.project}
- **Baseline Policy:** ${summary.baselineVersion}
- **Candidate Policy:** ${summary.candidateVersion}
- **Execution Run ID:** \`${summary.runId}\`
- **Timestamp:** ${summary.timestamp}

---

## EXECUTIVE VERDICT

# [ ${summary.status} ]

> **Policy Determination Rule:**
> If any critical authorization regression or tenant isolation failure exists, the candidate release is strictly **NOT PROVEN**.
> Current critical findings count: **${summary.criticalCount}**.

---

## METRIC BREAKDOWN

| Metric | Value |
| :--- | :--- |
| **Total Scenarios Evaluated** | ${summary.totalScenarios} |
| **Unchanged Decisions (Passing)** | ${summary.unchangedCount} |
| **Access Decision Deltas** | ${summary.changedCount} |
| **Critical Security Findings** | ${summary.criticalCount} |
| **Verification Decision** | **${summary.status}** |

---

## SECURITY FINDINGS BREAKDOWN

${findingsList || 'No authorization deltas detected.'}

---

## GENERATED REGRESSION TEST SUITE

The following test suites were deterministically derived from the minimal counterexamples to block future regressions in CI/CD:

${testsSection || 'No regression tests needed.'}

---
*PermitProof & Bob 2.0 Integration — Cryptographically deterministic authorization verification.*
`;
}

export function generateCertificateJSON(summary: ProofSummary): string {
  const payload = {
    certificateHeader: 'AUTHORIZATION CHANGE CERTIFICATE',
    engine: 'PermitProof v1.0.0',
    verificationMethod: 'Deterministic Differential Authorization Testing',
    project: summary.project,
    runId: summary.runId,
    timestamp: summary.timestamp,
    policyVersions: {
      baseline: summary.baselineVersion,
      candidate: summary.candidateVersion,
    },
    verdict: {
      status: summary.status,
      decisionRule: 'Zero tolerance for critical regressions or isolation breaches',
      criticalFindingsCount: summary.criticalCount,
    },
    metrics: {
      totalScenarios: summary.totalScenarios,
      unchangedDecisions: summary.unchangedCount,
      accessChanges: summary.changedCount,
      criticalFindings: summary.criticalCount,
    },
    findings: summary.findings.map((f) => ({
      id: f.id,
      severity: f.severity,
      classification: f.classification,
      role: f.role,
      resource: f.resource,
      action: f.action,
      conditions: f.conditions,
      baselineDecision: f.baselineDecision,
      candidateDecision: f.candidateDecision,
      summary: f.summary,
      generatedRegressionTest: generateRegressionTest(f),
    })),
  };

  return JSON.stringify(payload, null, 2);
}

export function exportCertificateFile(content: string, filename: string, type: 'text/markdown' | 'application/json') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
