import { Scenario } from '../types';

export const DETERMINISTIC_SCENARIOS: Scenario[] = [
  // 1-8: Super Admin Scenarios (Full access within tenant)
  {
    id: 'SCN-001',
    name: 'Super Admin reads Customer Profiles within tenant',
    role: 'Super Admin',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Verifies super admin read authorization under normal tenant conditions.',
  },
  {
    id: 'SCN-002',
    name: 'Super Admin exports Customer Profiles within tenant',
    role: 'Super Admin',
    resource: 'Customer Profiles',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Verifies super admin customer data export rights.',
  },
  {
    id: 'SCN-003',
    name: 'Super Admin deletes API Keys within tenant',
    role: 'Super Admin',
    resource: 'API Keys',
    action: 'delete',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Verifies administrative API key revocation rights.',
  },
  {
    id: 'SCN-004',
    name: 'Super Admin blocked by tenant boundary on Customer Profiles',
    role: 'Super Admin',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: false, owner: false, active: true },
    description: 'Ensures super admin credentials do not cross tenant isolation boundaries.',
  },
  {
    id: 'SCN-005',
    name: 'Super Admin blocked when account suspended',
    role: 'Super Admin',
    resource: 'Audit Logs',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: false },
    description: 'Ensures suspended super admin account is denied access.',
  },
  {
    id: 'SCN-006',
    name: 'Super Admin creates Project in tenant',
    role: 'Super Admin',
    resource: 'Projects',
    action: 'create',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Verifies project provisioning authority.',
  },
  {
    id: 'SCN-007',
    name: 'Super Admin updates Invoice',
    role: 'Super Admin',
    resource: 'Invoices',
    action: 'update',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Verifies invoice correction authority.',
  },
  {
    id: 'SCN-008',
    name: 'Super Admin reads Audit Logs',
    role: 'Super Admin',
    resource: 'Audit Logs',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Verifies audit visibility.',
  },

  // 9-16: Admin Scenarios
  {
    id: 'SCN-009',
    name: 'Admin reads Customer Profiles',
    role: 'Admin',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Standard admin tenant profile visibility.',
  },
  {
    id: 'SCN-010',
    name: 'Admin creates API Keys',
    role: 'Admin',
    resource: 'API Keys',
    action: 'create',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Admin key generation.',
  },
  {
    id: 'SCN-011',
    name: 'Admin cannot delete immutable Audit Logs',
    role: 'Admin',
    resource: 'Audit Logs',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Immutable compliance check preventing audit trail tampering.',
  },
  {
    id: 'SCN-012',
    name: 'Admin cannot update Audit Logs',
    role: 'Admin',
    resource: 'Audit Logs',
    action: 'update',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Audit log integrity protection.',
  },
  {
    id: 'SCN-013',
    name: 'Admin blocked across tenants for Invoices',
    role: 'Admin',
    resource: 'Invoices',
    action: 'read',
    conditions: { sameTenant: false, owner: false, active: true },
    description: 'Strict cross-tenant check on financial records.',
  },
  {
    id: 'SCN-014',
    name: 'Admin blocked when suspended',
    role: 'Admin',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: false },
    description: 'Suspended admin account enforcement.',
  },
  {
    id: 'SCN-015',
    name: 'Admin exports Customer Profiles',
    role: 'Admin',
    resource: 'Customer Profiles',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Authorized compliance data export.',
  },
  {
    id: 'SCN-016',
    name: 'Admin deletes Project',
    role: 'Admin',
    resource: 'Projects',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Administrative resource cleanup.',
  },

  // 17-26: Manager Scenarios
  {
    id: 'SCN-017',
    name: 'Manager reads departmental Invoices',
    role: 'Manager',
    resource: 'Invoices',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Departmental billing visibility.',
  },
  {
    id: 'SCN-018',
    name: 'Manager creates Invoices',
    role: 'Manager',
    resource: 'Invoices',
    action: 'create',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Invoice creation workflow.',
  },
  {
    id: 'SCN-019',
    name: 'Manager deletes owned Invoice',
    role: 'Manager',
    resource: 'Invoices',
    action: 'delete',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Manager retracting their own draft invoice.',
  },
  {
    // REGRESSION TRIGGER 2: Manager deleting unowned invoice
    id: 'SCN-020',
    name: 'Manager deletes unowned Invoice (Owner check constraint)',
    role: 'Manager',
    resource: 'Invoices',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Managers must NOT delete invoices authored by others.',
  },
  {
    id: 'SCN-021',
    name: 'Manager cannot export Invoices',
    role: 'Manager',
    resource: 'Invoices',
    action: 'export',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Raw financial export barred for non-admins.',
  },
  {
    id: 'SCN-022',
    name: 'Manager cannot access API Keys',
    role: 'Manager',
    resource: 'API Keys',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Restricted secret access.',
  },
  {
    id: 'SCN-023',
    name: 'Manager cannot inspect Audit Logs',
    role: 'Manager',
    resource: 'Audit Logs',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Audit log restricted to compliance roles.',
  },
  {
    id: 'SCN-024',
    name: 'Manager updates owned Project',
    role: 'Manager',
    resource: 'Projects',
    action: 'update',
    conditions: { sameTenant: true, owner: true, active: true },
    description: 'Project management flow.',
  },
  {
    id: 'SCN-025',
    name: 'Manager deletes unowned Project',
    role: 'Manager',
    resource: 'Projects',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Unowned project deletion denied.',
  },
  {
    id: 'SCN-026',
    name: 'Manager blocked cross-tenant on Invoices',
    role: 'Manager',
    resource: 'Invoices',
    action: 'read',
    conditions: { sameTenant: false, owner: false, active: true },
    description: 'Cross-tenant protection on invoices.',
  },

  // 27-36: Support Scenarios
  {
    id: 'SCN-027',
    name: 'Support reads Customer Profiles for assistance',
    role: 'Support',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support agent looks up customer data for ticket resolution.',
  },
  {
    id: 'SCN-028',
    name: 'Support updates Customer Profiles for ticket resolution',
    role: 'Support',
    resource: 'Customer Profiles',
    action: 'update',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support agent updates contact email upon customer request.',
  },
  {
    // REGRESSION TRIGGER 1: Support exporting Customer Profiles
    id: 'SCN-029',
    name: 'Support exports Customer Profiles (PII data leakage constraint)',
    role: 'Support',
    resource: 'Customer Profiles',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support personnel must NEVER export bulk customer profile databases.',
  },
  {
    id: 'SCN-030',
    name: 'Support cannot delete Customer Profiles',
    role: 'Support',
    resource: 'Customer Profiles',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support personnel cannot permanently purge customer records.',
  },
  {
    id: 'SCN-031',
    name: 'Support reads Projects for system diagnostics',
    role: 'Support',
    resource: 'Projects',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support agent viewing project metadata.',
  },
  {
    id: 'SCN-032',
    name: 'Support cannot modify Projects',
    role: 'Support',
    resource: 'Projects',
    action: 'update',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Support cannot alter customer project contents.',
  },
  {
    // REGRESSION TRIGGER 3: Tenant isolation check missing for Internal Notes
    id: 'SCN-033',
    name: 'Support reads Internal Notes across different tenants (Isolation check)',
    role: 'Support',
    resource: 'Internal Notes',
    action: 'read',
    conditions: { sameTenant: false, owner: false, active: true },
    description: 'Cross-tenant notes access must be strictly forbidden under multi-tenancy rules.',
  },
  {
    id: 'SCN-034',
    name: 'Support reads Internal Notes in same tenant',
    role: 'Support',
    resource: 'Internal Notes',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Authorized case note review within same tenant.',
  },
  {
    id: 'SCN-035',
    name: 'Support cannot access API Keys',
    role: 'Support',
    resource: 'API Keys',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Secret isolation from support staff.',
  },
  {
    id: 'SCN-036',
    name: 'Support reads Audit Logs for incident verification',
    role: 'Support',
    resource: 'Audit Logs',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Read-only access to audit logs for user ticket investigation.',
  },

  // 37-43: Analyst Scenarios
  {
    id: 'SCN-037',
    name: 'Analyst reads Customer Profiles',
    role: 'Analyst',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Analyst viewing customer metrics.',
  },
  {
    id: 'SCN-038',
    name: 'Analyst exports Projects for metric reporting',
    role: 'Analyst',
    resource: 'Projects',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Project telemetry export.',
  },
  {
    id: 'SCN-039',
    name: 'Analyst exports Invoices for financial summaries',
    role: 'Analyst',
    resource: 'Invoices',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Quarterly financial report aggregation.',
  },
  {
    id: 'SCN-040',
    name: 'Analyst cannot create Invoices',
    role: 'Analyst',
    resource: 'Invoices',
    action: 'create',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Separation of duties preventing analysts from invoicing.',
  },
  {
    id: 'SCN-041',
    name: 'Analyst cannot delete Customer Profiles',
    role: 'Analyst',
    resource: 'Customer Profiles',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Analyst cannot delete master records.',
  },
  {
    id: 'SCN-042',
    name: 'Analyst cannot read API Keys',
    role: 'Analyst',
    resource: 'API Keys',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Credential shielding.',
  },
  {
    id: 'SCN-043',
    name: 'Analyst blocked across tenants on Projects',
    role: 'Analyst',
    resource: 'Projects',
    action: 'read',
    conditions: { sameTenant: false, owner: false, active: true },
    description: 'Tenant isolation on project data.',
  },

  // 44-50: Viewer & Boundary Scenarios
  {
    id: 'SCN-044',
    name: 'Viewer reads Customer Profiles in tenant',
    role: 'Viewer',
    resource: 'Customer Profiles',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Standard viewer read access.',
  },
  {
    id: 'SCN-045',
    name: 'Viewer cannot delete Customer Profiles',
    role: 'Viewer',
    resource: 'Customer Profiles',
    action: 'delete',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Viewer role mutation prevention.',
  },
  {
    // REGRESSION TRIGGER 5: Viewer incorrectly receives UPDATE permission for Projects
    id: 'SCN-046',
    name: 'Viewer updates Projects (Unauthorized privilege escalation)',
    role: 'Viewer',
    resource: 'Projects',
    action: 'update',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Viewers must never have write/update access to Projects.',
  },
  {
    id: 'SCN-047',
    name: 'Viewer cannot export Projects',
    role: 'Viewer',
    resource: 'Projects',
    action: 'export',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Restricted export for viewers.',
  },
  {
    // REGRESSION TRIGGER 4: Suspended users incorrectly retain access to Projects
    id: 'SCN-048',
    name: 'Suspended user attempts to read Projects (Account state bypass)',
    role: 'Viewer',
    resource: 'Projects',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: false },
    description: 'Suspended accounts must have all access revoked across all resources.',
  },
  {
    id: 'SCN-049',
    name: 'Viewer cannot access API Keys',
    role: 'Viewer',
    resource: 'API Keys',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Zero credential access for viewers.',
  },
  {
    id: 'SCN-050',
    name: 'Viewer cannot access Audit Logs',
    role: 'Viewer',
    resource: 'Audit Logs',
    action: 'read',
    conditions: { sameTenant: true, owner: false, active: true },
    description: 'Security audit logs protected from casual viewers.',
  },
];
