import { Finding } from '../types';

/**
 * Generates an automated regression test snippet for Vitest / Jest
 * targeting the specific unauthorized candidate policy behavior.
 */
export function generateRegressionTest(finding: Finding): string {
  const roleName = finding.role;
  const resourceName = finding.resource;
  const actionName = finding.action;
  const testTitle = `${roleName} cannot ${actionName} ${resourceName} under ${
    !finding.conditions.sameTenant
      ? 'cross-tenant condition'
      : !finding.conditions.active
      ? 'suspended account state'
      : !finding.conditions.owner
      ? 'unowned resource condition'
      : 'policy constraints'
  }`;

  return `// Automated Regression Test generated by PermitProof
// Finding ID: ${finding.id} (${finding.classification})
// Severity: ${finding.severity}
import { describe, it, expect } from 'vitest';
import { evaluateCandidate } from './candidate';

describe("Authorization Regression Guard: ${testTitle}", () => {
  it("strictly enforces expected DENY policy decision", () => {
    // Counterexample scenario parameters
    const scenario = {
      role: "${roleName}",
      resource: "${resourceName}",
      action: "${actionName}",
      conditions: {
        sameTenant: ${finding.conditions.sameTenant},
        owner: ${finding.conditions.owner},
        active: ${finding.conditions.active},
      },
    };

    const result = evaluateCandidate(scenario);

    // Expected baseline compliance: DENY
    // Detected candidate regression was: ${finding.candidateDecision}
    expect(result.decision).toBe("DENY");
  });
});
`;
}
